# Generated by Django 6.0.5 on 2026-05-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solidaritymessage',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
