# Generated by Django 6.0.5 on 2026-05-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_solidaritymessage_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='solidaritymessage',
            name='sender_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=100),
        ),
    ]
