# Generated by Django 6.0.5 on 2026-05-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('say_names', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('killed', 'Killed'), ('jailed', 'Jailed'), ('injured', 'Injured'), ('missing', 'Missing')], max_length=20)),
                ('date_of_incident', models.DateField(blank=True, null=True)),
                ('how_it_happened', models.TextField()),
                ('additional_info', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='victims/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
