# Generated by Django 6.0.5 on 2026-05-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('say_names', '0002_victim_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='approval',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
