# Generated by Django 6.0.5 on 2026-05-25 06:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('county', models.CharField(max_length=50)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('subscription_fee', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('subscription_expires', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
